### ISSUE TITLE
Migrate routing definitions to newer syntax

### ISSUE THREAD

**Issue by tehplague** [azine/AzineMailgunWebhooksBundle#1]
The current routing definitions trigger deprecation notices in Symfony 2.8 as you can see below

```
DEPRECATED - The "pattern" option in file "/path/to/app/vendor/azine/mailgunwebhooks-bundle/Azine/MailgunWebhooksBundle/Resources/config/routing/mailgunevent_webhook.yml" is deprecated since version 2.2 and will be removed in 3.0. Use the "path" option in the route definition instead.
```

Simply replacing all occurrences of `pattern` with `path` should do the trick.

**Comment by azine** [comment]
Hi,

Thanx for the info.

I'll do the migration soon.  If you are in a hurry, please submitt a pull-request.

Cheers,
Dominik

**Comment by azine** [comment]
Got around to fix this earlier than expected. :-) see the new tag 1.2.0

**Comment by tehplague** [comment]
Hi @azine,

I needed to reopen this again. The `pattern` option has been fixed but there is the `_method` requirement that has been deprecated, too.

```
The "_method" requirement of route "mailgunevent_webhook" in file "/path/to/vendor/azine/mailgunwebhooks-bundle/Azine/MailgunWebhooksBundle/Resources/config/routing/mailgunevent_webhook.yml" is deprecated since version 2.2 and will be removed in 3.0. Use the "methods" option instead.
```

Since the deprecation originated from Symfony 2.2 there shouldn't be any problem to fix this while keeping BC.

**Comment by azine** [comment]
thanx for the hint. I updated the routing pattern and also the Twig-Filter.

Cheers,
d.
