### ISSUE TITLE
Move code into a src/ directory, and change to PSR-4 autoloading

### ISSUE THREAD

**Issue by alister** [azine/AzineMailgunWebhooksBundle#12]
`No whitelist configured, no code coverage will be generated`. Moving the code files into a sub-directory allows for easier phpunit.xml configuration, and tidy up the root of the project. `Tests/` can stay in the root.

Migrating to PSR-4 style loading is also best practice, but any changes there should be transparent with the use of Composer.

**Comment by azine** [comment]
updated project structure.
