### ISSUE TITLE
[RFC] Deprecate testing against old versions (PHP & framework) for v2

### ISSUE THREAD

**Issue by alister** [azine/AzineMailgunWebhooksBundle#14]
* Require and test against 7.1, 7.2/nightly (allowing failures against nightly)
* Test against Symfony 2.8, ^3.3, & dev-latest, for LTS & latest versions

With a move to a PHP 7 code-base, we can  also move to PHPunit ^6.0.

Are people still actively using PHP 5?

**Comment by azine** [comment]
I still use php 5.6. ;-) 
A lot of applications are developed and deployed and keep running for years. So I also guess I am not alone still usng 5.6
I think all the other suggestions are fixed with your PR #17. Right?
