### ISSUE TITLE
./Commands/*.php not auto-registered as of Symfony 3.4

### ISSUE THREAD

**Issue by alister** [azine/AzineMailgunWebhooksBundle#15]
Auto-registration of the command "Azine\MailgunWebhooksBundle\Command\DeleteOldEntriesCommand" is deprecated since Symfony 3.4

it's an easy fix though. They can be [autoconfigured](https://symfony.com/blog/new-in-symfony-3-3-simpler-service-configuration#combining-default-and-interface-based-configuration) (with Symfony 3.3+) or for backward compatibility, added to the services.yml file and tagged `tags: ['console.command']`.

With services in 3.4/4.0+ also being made private by default, it may also be good to convert the commad from `extends ContainerAwareCommand` to a service (`extends Command`), and injecting requirements in the constructor, instead of `$this->getContainer()->get('azine_mailgun.service');` (in `getMailgunService()`).

**Comment by azine** [comment]
That all sounds like good ideas. 
I must admit I am still using Symfony 2.7 (and will be using 2.7 for a while longer), so updating to 3.* was not on any priority list so far. :-/
Do you have time to create a PR for this?

**Comment by alister** [comment]
I'll do what I can in the next couple of days. I've already done so for [another project](/DZunke/SlackBundle/pull/33). If you want to keep 2.7 compatibility, I'll just create a service name (if 2.7 doesn't like class-names) and tag it, and then see about the constructor and add that to the service.

**Comment by azine** [comment]
fixed with #17 
Thanks @alister

**Comment by alister** [comment]
Re the comment on #14, this was just the 'quick fix', as the `getContainer()->get('azine_mailgun.service')` is still there, but the service is explicitly public, and so so the 3.4 test passes, but it, and the other container->get's need to be put into the constructor eventually, and drop the `extends ContainerAwareCommand`.
