### ISSUE TITLE
Make AzineMailgunWebhooksBundle compatible with Symfony 4

### ISSUE THREAD

**Issue by tehplague** [azine/AzineMailgunWebhooksBundle#16]
As of Symfony Flex, directly requiring `symfony/symfony` does not work anymore. Instead, you should require only exactly the components you need, e.g. `symfony/routing`, `symfony/translation` and so on.

Otherwise - and this is currently the case - this bundle won't work with Symfony Flex and/or Symfony 4.

**Comment by Metabor** [comment]
Run into the same issue. This bundle is not compatible with symfony flex. :(
