### ISSUE TITLE
update README

### ISSUE THREAD

**Issue by thoroc** [azine/AzineMailgunWebhooksBundle#2]
Symfony 3+ changed ```app/console``` to ```bin/console``` and ```router:debug``` to ```debug:router```.

So 
``` sh
    php app/console router:debug -e prod | grep mailgunevent_webhook
```

should be 
``` sh
    php bin/console debug:router -e prod | grep mailgunevent_webhook
```

**Comment by azine** [comment]
Thanx for the notice. I changed it. Anything else that needs to be updated? (I'm still on Symfony 2.7 with my apps)
