### ISSUE TITLE
mailgun api event 'dropped' not recognised in DeleteOldEntriesCommand

### ISSUE THREAD

**Issue by alister** [azine/AzineMailgunWebhooksBundle#22]
'dropped' is not listed as a known event-type in DeleteOldEntriesCommand.php (help text, and `array_search`).

**Comment by azine** [comment]
True, must be a new event-type.

**Comment by azine** [comment]
hmmmm... https://documentation.mailgun.com/en/latest/api-events.html#event-types and https://documentation.mailgun.com/en/latest/api-webhooks.html#webhooks don't seem to use the same event types.

I never paid attention to the content of the "event" field. I guess the list in DeleteOldEntriesCommand.php (and with it the event types in other places in the bundle) is wrong. 

It should be: 
- bounced*
- delivered* 
- dropped*
- opened*
- spam
- unsubscribe
- click

I can see entries of types with * above in my applications database.

**Comment by azine** [comment]
added to event-list with https://github.com/azine/AzineMailgunWebhooksBundle/commit/f46ee68d6bb9aebae48f17025cb62e8de3b86bcc
