### ISSUE TITLE
Xliff/Translations fatal error

### ISSUE THREAD

**Issue by alister** [azine/AzineMailgunWebhooksBundle#27]
After I updated to the latest version, every pages throws this exception:

An exception has been thrown during the rendering of a template ("Invalid resource provided: "1.2"; Errors: [ERROR 1867] Element '{urn:oasis:names:tc:xliff:document:1.2} source', attribute 'state': The attribute 'state' is not allowed. (in /home/.../web/ - line 14, column 0)

The [Xliff schema](http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#state) does  mention 'state', but it's not on `source`, its on the next element - `target`.

Also: https://github.com/azine/AzineMailgunWebhooksBundle/pull/18#discussion_r149360296

**Comment by azine** [comment]
fixed with commit https://github.com/azine/AzineMailgunWebhooksBundle/commit/706331b09f8bc73eb9f0942f1b332722963200bf
