### ISSUE TITLE
Symfony 6, Php 8.1 compatibility

### ISSUE THREAD

**Issue by ovgray** [azine/AzineMailgunWebhooksBundle#55]
Do you have any plan to update this bundle so that it can be used in Symfony 6, Php 8.1?

**Comment by azine** [comment]
Hi,

I didn't look into this yet, but likely yes at some (not so near) point in
time.

I'd love to see a PR though and would the prioritize merging/testing it.

Cheers,
D.

**Comment by azine** [comment]
I updated the composer.json. Didn't test extensively, but it looks like it works.
