### ISSUE TITLE
MailgunEvent field lengths can be too large for the database fields

### ISSUE THREAD

**Issue by alister** [azine/AzineMailgunWebhooksBundle#8]
While developing some emails to be sent from my application, I sent an email from dev that was sent through Mailgun, and so generated an event. 

However, the bundle attempted to insert the string 'Unknown' into the 'country' field (and would have tried to do the same for 'region'). 'Country' has a DB length of 2 characters, 'region' has a length of 4.  In the [events documentation](http://mailgun-documentation.readthedocs.io/en/latest/api-events.html#event-structure), one example 'region' is also given as 'Texas' (for the 'opened' event).

**Comment by azine** [comment]
Did you find any documentation on the length of those fields? Feels bad to just make them "text" based on a wild guess.

Handling "unkown": how about just not setting the value in the created event if the reported value is "unknown"?

**Comment by alister** [comment]
I've asked Mailgun support if there are any specific length limits for fields in the event payload, but even then, I think just suppressing the properties from being set for 'country' & 'region' if they are "Unknown" would be a pragmatic and quick fix in the meantime. There is a country code for 'unknown' ('XX'), but I think that would confuse more than just a blank/null contents, and most of the fields are nullable anyway.

I'll start work on a pull request to ignore an "Unknown" in the two fields.

**Comment by azine** [comment]
Thanks for you PR. Let's keep this issue open until you hear from Mailgun support about the field length.

**Comment by alister** [comment]
From Mailgun support:
> Currently, there isn't specified limits on the lengths of each field POSTed to Webhooks. You may capture a sample output from the Webhooks page -> Test webhook. This will post a sample to the webhooks with data you may expect from our side. 

I think we will just need to wait and see what reports may come in, and maybe add some code for defence - such as the already merged 'Unknown' handling.  Explicit length checks, and cutting off over-long data may be required, but this might issues if the MailgunEvent.orm.yml was overridden, or otherwise altered.

It will probably have to happen though, because the webhook delivery will keep retrying to deliver the same data.

**Comment by azine** [comment]
What a nice API spec. "Spec by a few examples." Yuck! Oh well, I guess we have to live with that.

How about setting the length of both strings to 31for Region and to 7 for Country (so 'Unknown' fits in) in MailgunEvent.orm.yml and add logic to MailgunEvent.php to truncate data that is too long?!

**Comment by alister** [comment]
I think that's sensible. I'd also suggest taking the bundle to v2.0 as well, as the [database could be seen as part of the public API](https://github.com/mojombo/semver/issues/90). Since it would generate a database schema change, a big, bold message in a CHANGELOG would give users the opportunity to plan and prepare for it.  Putting the truncations into a 1.x (and them modified for changes in the field lengths) would be a good intermediate step.

There are a couple of other issues I'd like to take care of before that  as well, I'll add some issues for them.
